### ISSUE TITLE
submissions/id からテストケースを見れるようにする

### ISSUE THREAD

**Issue by kisepichu** [tqkoh/qkjudge-UI#1]
WJ のときの progress も表示sるう

**Comment by tqkoh** [comment]
okk https://github.com/tqkoh/qkjudge-UI/commit/ed560cb37bdb7cb472f0f59612f5cb8140f32b0b

**Comment by kisepichu** [comment]
okk https://github.com/tqkoh/qkjudge-UI/commit/ed560cb37bdb7cb472f0f59612f5cb8140f32b0b
